pipeline{
agent any
stages{
stage('vcs'){
steps{
 git branch: 'main',
      url: 'https://github.com/glaxma/finance.git'
}

}
stage('test'){
 steps{
    bat "mvn -Dmaven.test.failure.ignore=true clean package"
  }
}
}
}